<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kode Instansi_instanceCode</name>
   <tag></tag>
   <elementGuidId>8a7db17a-67aa-41c4-94fe-04030d3491ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kodeInstansiAdd']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#kodeInstansiAdd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>16eee868-5288-4948-a265-8d961c57bef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>39622cc6-2c6c-47ae-b82b-a3f5a96db8df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cb7aa838-7cbd-4a7a-bf37-633429a9bfeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kodeInstansiAdd</value>
      <webElementGuid>dc175d7a-0c19-484b-972c-8c539d3c2172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>instanceCode</value>
      <webElementGuid>65dc0ed9-db39-4c8d-a554-447649e21889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kode Instansi</value>
      <webElementGuid>87ea1b8f-de23-4684-a5c7-14d8ed60d461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>14343052-34d4-473a-8345-1f66c2ec180a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kodeInstansiAdd&quot;)</value>
      <webElementGuid>0f96d3ff-1cdf-4bac-b577-42d7913d5ca4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kodeInstansiAdd']</value>
      <webElementGuid>be8e37fa-62f0-451d-937d-b7d9e18c3a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[2]/input</value>
      <webElementGuid>adb5b036-c4bd-4c8f-a3d1-8fe7d16cf7c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/form/div[2]/div[2]/input</value>
      <webElementGuid>51703891-83dc-4022-92a9-de64cf394e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @class = 'form-control' and @id = 'kodeInstansiAdd' and @name = 'instanceCode' and @placeholder = 'Kode Instansi']</value>
      <webElementGuid>4c2235ee-9d2c-40ee-8add-dae28d5b9a90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
