<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>logo_header</name>
   <tag></tag>
   <elementGuidId>ba83e638-3820-4cb3-8218-b8e153ac189c</elementGuidId>
   <imagePath>Screenshots/Targets/Page_Home  Indocyber/logo_header.png</imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Logo Indocyber&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_Home  Indocyber/logo_header.png</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>74dbc968-6584-4467-9b1b-dcf0ca7327cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo Indocyber</value>
      <webElementGuid>d447a21e-ece5-43e8-a173-d59caa6cae19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Flogo-iglo.13052c31.png&amp;w=96&amp;q=75 1x, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Flogo-iglo.13052c31.png&amp;w=256&amp;q=75 2x</value>
      <webElementGuid>c2a30d7f-34b2-4b6a-8145-a76fad205d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Flogo-iglo.13052c31.png&amp;w=256&amp;q=75</value>
      <webElementGuid>323c020d-6880-40bb-9940-ad207854c997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>67</value>
      <webElementGuid>97517345-b593-43c5-a29b-cbff0a520970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>54</value>
      <webElementGuid>fb0d5b7a-7716-467e-a549-6467b114864d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>dcc2bfcd-b578-481a-91df-c94e139042db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a3709642-1c17-4349-9971-c6b70c9d2242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>46e7fcc8-92ae-4ac4-9b9b-d8be4431fe8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;style_headerWrapper__ffo9A style_bgLight__poLOJ&quot;]/div[1]/div[@class=&quot;container&quot;]/div[@class=&quot;style_navbarWrapper__cL__c&quot;]/a[@class=&quot;style_navbarBrand__6GCED&quot;]/img[1]</value>
      <webElementGuid>521354e5-a465-4cc2-b170-71851c2a305d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/a/img</value>
      <webElementGuid>ade8278d-7dbe-443f-a53b-6f71ad2edf7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Logo Indocyber']</value>
      <webElementGuid>a053abe3-3589-4ecd-8449-e0bc5a877268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>8dece103-598b-4cd3-b3b5-361c73829128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Logo Indocyber' and @src = '/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Flogo-iglo.13052c31.png&amp;w=256&amp;q=75']</value>
      <webElementGuid>2c11ff2a-230a-44da-80e5-98ff8845e7df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
