<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Indonesian_mw-file-element</name>
   <tag></tag>
   <elementGuidId>5bc9bbeb-7f9c-4e01-ac0c-154ba7be4209</elementGuidId>
   <imagePath>C:\Users\1878\OneDrive\Desktop\Latihan Katalon Training FIF\Latihan Training Katalon\Screenshots\Targets\Page_Indonesia - Wikipedia\img_Indonesian_mw-file-element.png</imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mw-content-text']/div/table/tbody/tr[2]/td/div/div/div/span/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.mw-file-description > img.mw-file-element</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>C:\Users\1878\OneDrive\Desktop\Latihan Katalon Training FIF\Latihan Training Katalon\Screenshots\Targets\Page_Indonesia - Wikipedia\img_Indonesian_mw-file-element.png</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;mw-content-text&quot;)/div[@class=&quot;mw-content-ltr mw-parser-output&quot;]/table[@class=&quot;infobox ib-country vcard&quot;]/tbody[1]/tr[2]/td[@class=&quot;infobox-image&quot;]/div[@class=&quot;noresize&quot;]/div[1]/div[1]/span[@class=&quot;mw-image-border&quot;]/a[@class=&quot;mw-file-description&quot;]/img[@class=&quot;mw-file-element&quot;][count(. | //*[@alt = 'Flag of Indonesia' and @src = '//upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/125px-Flag_of_Indonesia.svg.png']) = count(//*[@alt = 'Flag of Indonesia' and @src = '//upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/125px-Flag_of_Indonesia.svg.png'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0bf2ad7c-dcaa-4c62-aebb-6de50f725572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Flag of Indonesia</value>
      <webElementGuid>6eaa63c6-c71b-4fce-aff7-afbba9afe9eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/125px-Flag_of_Indonesia.svg.png</value>
      <webElementGuid>d635157e-9df5-4c6f-ac88-31cf51f1c910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>4e52d695-6ad8-4e89-bbb3-3606d98abe25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>125</value>
      <webElementGuid>6ee7d753-4242-44f4-bead-3dcfb9f058f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>83</value>
      <webElementGuid>9b312705-ccf5-4b0b-b172-1aa139793f72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mw-file-element</value>
      <webElementGuid>2fd386dd-1d74-418c-92c3-dcaae7d47ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>//upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/188px-Flag_of_Indonesia.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/250px-Flag_of_Indonesia.svg.png 2x</value>
      <webElementGuid>fa07f3c8-180f-4567-bd69-98352bde31da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-file-width</name>
      <type>Main</type>
      <value>900</value>
      <webElementGuid>c8e1b36d-1a58-44da-9d54-f88c9dafc14c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-file-height</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>e6370ba2-6f1d-4e8c-89f8-51cad8d28540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mw-content-text&quot;)/div[@class=&quot;mw-content-ltr mw-parser-output&quot;]/table[@class=&quot;infobox ib-country vcard&quot;]/tbody[1]/tr[2]/td[@class=&quot;infobox-image&quot;]/div[@class=&quot;noresize&quot;]/div[1]/div[1]/span[@class=&quot;mw-image-border&quot;]/a[@class=&quot;mw-file-description&quot;]/img[@class=&quot;mw-file-element&quot;]</value>
      <webElementGuid>ccd757cb-f561-4d9c-bef9-798896fb941e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mw-content-text']/div/table/tbody/tr[2]/td/div/div/div/span/a/img</value>
      <webElementGuid>0d679ae9-216f-4cae-a5b4-16dd021bc7b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Flag of Indonesia']</value>
      <webElementGuid>30a8b3cf-8d11-4871-b1ef-a3e2f68595ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/div/span/a/img</value>
      <webElementGuid>9d6697d7-eb94-48f9-bafc-33502d9bf061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Flag of Indonesia' and @src = '//upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/125px-Flag_of_Indonesia.svg.png']</value>
      <webElementGuid>f290667a-54b2-4cd3-a9b3-a6141cdeaa02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
