<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Category_wanita</name>
   <tag></tag>
   <elementGuidId>d6014a81-9258-479a-810c-39d0699219ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header/div[3]/div/div[2]/div/nav/ul/li[1]/a[contains(@href,'https://www.matahari.com/landing-wanita')]/span[contains(text(),'WANITA')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>43fa34ba-1c58-4077-8c73-ebcc053026a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1703569807969</value>
      <webElementGuid>67861d47-c5fb-4e05-b76d-5a4626d1c93f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
