<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>List_value</name>
   <tag></tag>
   <elementGuidId>9bf2a2b3-a016-4d0b-9358-75cca1962ddf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='pic' and @id='picAdd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>e864a3af-6017-41e6-afc9-b4ce968a528a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1705414054551</value>
      <webElementGuid>0591b79d-d598-47d3-86a6-7beaf3bc89ba</webElementGuid>
   </webElementProperties>
</WebElementEntity>
