<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gettexterror</name>
   <tag></tag>
   <elementGuidId>1417141c-62ce-4a32-8c36-8b0a5b7f2590</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div/form/div[1]/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>09f0c4ff-16ef-4678-915d-2535155057a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1703144536625</value>
      <webElementGuid>0fd9d57e-5152-43ef-8a93-2654647ec719</webElementGuid>
   </webElementProperties>
</WebElementEntity>
