<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Active_btnDelete</name>
   <tag></tag>
   <elementGuidId>918d187b-ef26-4af4-906a-7b80031a04b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnDelete']/preceding::button[@id='btnEdit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnDelete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>34f2be32-3061-4c18-9f3e-571a095f3cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c882fb16-b942-4fe9-8fa7-a3533ced1103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger btn-xs btn-pill</value>
      <webElementGuid>02729ce7-e089-4847-9ea2-08a2a38379da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnDelete</value>
      <webElementGuid>3701b062-75e8-4d76-916e-8ba1d350e912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>4f34347b-69a4-474f-8a33-1cc565fb1640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>16c9ef8a-35f9-4d7e-88c0-17bcae4d3aa6</value>
      <webElementGuid>0281a081-402e-45f5-b14b-979913f31a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;branch-table&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/button[@id=&quot;btnDelete&quot;]</value>
      <webElementGuid>d14fd629-96e3-4d88-ad79-c4a648fd0bd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnDelete']</value>
      <webElementGuid>c1caadd1-d36a-42ba-b739-a94cefd38495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='branch-table']/tbody/tr/td/button[2]</value>
      <webElementGuid>df39fe96-a449-4db5-a2dc-45587cdf9ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/button[2]</value>
      <webElementGuid>9b3d6fb7-1cc2-4bd3-8197-50589cdae531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @class = 'btn btn-danger btn-xs btn-pill' and @id = 'btnDelete' and @title = 'Delete']</value>
      <webElementGuid>2c487a33-3351-400b-84d1-adf1f67a0917</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
