<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>element_btn_login</name>
   <tag></tag>
   <elementGuidId>f464cdbf-5895-47cf-bcea-19c73d121b6b</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[(@action='/Application/Account/Login')]/div[3]/button[contains(@id,'btnLogin') or (@type='submit')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>9a923e8e-1280-485a-97a4-8d6792ef087f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1703820406274</value>
      <webElementGuid>674959b9-14ce-47a3-b540-1a992c932d40</webElementGuid>
   </webElementProperties>
</WebElementEntity>
