<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Logo_starbridges_ss</name>
   <tag></tag>
   <elementGuidId>fa235944-8a87-4c81-bbee-0aeb9b11fa3f</elementGuidId>
   <imagePath>Screenshots/Targets/Page_Login/Logo_starbridges_ss.png</imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div/div/img[contains(@src,'/Application/Content/Images/logo.png')]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_Login/Logo_starbridges_ss.png</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6c7d485f-09f6-499a-ad6a-b91ec5f77270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Application/Content/Images/logo.png</value>
      <webElementGuid>ec89200b-d40b-43a5-9e06-712cb1fbc1ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;k-webkit k-webkit120 js  js csstransforms3d csstransitions&quot;]/body[1]/div[@class=&quot;left-login&quot;]/div[@class=&quot;login-logo&quot;]/img[1]</value>
      <webElementGuid>34d8ca0b-e564-4666-bf36-ab0f18f958cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>35ea5576-df56-4e3f-9f52-e5d60ada2aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/Application/Content/Images/logo.png']</value>
      <webElementGuid>09e473a0-ed50-4228-bbd7-3db78fe8dcd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
