<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Logo_starbridges_ss</name>
   <tag></tag>
   <elementGuidId>fa235944-8a87-4c81-bbee-0aeb9b11fa3f</elementGuidId>
   <imagePath>Screenshots/Targets/Page_Login/Logo_starbridges_ss.png</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_Login/Logo_starbridges_ss.png</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div/div/img[contains(@src,'/Application/Content/Images/logo.png')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3f4e0d3a-768f-467d-bdff-1513e1818a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Application/Content/Images/logo.png</value>
      <webElementGuid>879ae69d-85f0-49b5-abce-647a5c9864b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;k-webkit k-webkit120 js  js csstransforms3d csstransitions&quot;]/body[1]/div[@class=&quot;left-login&quot;]/div[@class=&quot;login-logo&quot;]/img[1]</value>
      <webElementGuid>6bb18bd7-4536-44b9-b7f6-78ebec5ed55d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>b91251b7-841e-44c0-8b43-d56fdbea152c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/Application/Content/Images/logo.png']</value>
      <webElementGuid>fd76b4c6-6dd0-42c9-895e-a22b98fdc761</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
